version: '3.8'
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=capim
      - POSTGRES_PASSWORD=capim
      - POSTGRES_DB=capim
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local